spring:
  application:
    name: booting
---
spring:
  config:
    activate:
      on-profile: dev
server:
  port: 9090
---
spring:
  config:
    activate:
      on-profile: test
server:
  port: 9000
---
spring:
  config:
    activate:
      on-profile: prod
server:
  port: 9001
